import React from "react";
import DepigmentI from "../Imagenes/Depigment I.jpg";
import HydrateI from "../Imagenes/Hydrate I.jpg";
import HydrateII from "../Imagenes/Hydrate II.jpg";
import RenewI from "../Imagenes/Renew I.jpg";
import RenewII from "../Imagenes/Renew II.jpg";
import RestructureI from "../Imagenes/Restructure I.jpg";
import RestructureII from "../Imagenes/Restructure II.jpg";
import ShotAntiAging from "../Imagenes/Shot AntiAging.png";
import ShotHydratation from "../Imagenes/Shot Hydratation.png";
import ShotRegeneration from "../Imagenes/Shot Regeneration.png";
import Treatment from "../Imagenes/Treatment.png";

export const data = [
    {
      id: 1,
      categoria:1,
      nombre: "Despigmentación I",
      stock: 20,
      precio: "S 1500",
      imagen: DepigmentI,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 2,
      categoria:1,
      nombre: "Hidratación I",
      stock: 40,
      precio: "S 1500",
      imagen: HydrateI,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 3,
      categoria:1,
      nombre: "Hidratación II",
      stock: 10,
      precio: "S 1500",
      imagen: HydrateII,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 4,
      categoria:1,
      nombre: "Renovación I",
      stock: 10,
      precio: "S 1500",
      imagen: RenewI,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 5,
      categoria:1,
      nombre: "Renovación II",
      stock: 13,
      precio: "S 1500",
      imagen: RenewII,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 6,
      categoria:1,
      nombre: "Reestructuración I",
      stock: 10,
      precio: "S 1500",
      imagen: RestructureI,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 7,
      categoria:1,
      nombre: "Reestructuración II",
      stock: 10,
      precio: "S 1500",
      imagen: RestructureII,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 8,
      categoria:2,
      nombre: "Shot Anti-Age",
      stock: 7,
      precio: "S 3000",
      imagen: ShotAntiAging,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 9,
      categoria:2,
      nombre: "Shot Hidratación",
      stock: 7,
      precio: "S 3000",
      imagen: ShotHydratation,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 10,
      categoria:2,
      nombre: "Shot Regeneración",
      stock: 7,
      precio: "S 3000",
      imagen: ShotRegeneration,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
    {
      id: 11,
      categoria:3,
      nombre: "Tratamiento Renovación Celular",
      stock: 5,
      precio: "S 9500",
      imagen: Treatment,
      titulo:"Crema facial ANTI-AGING II",
      descripcion:"Crema facial con Argireline + Leuphasyl + Rosa Mosqueta Liposomada para uso de día. Apta para todo tipo de piel.",
      accion: "Acción: Crema con componentes específicos para darle a la piel un aspecto saludable.",
      modouso: "Modo de uso: Limpiar el rostro, cuello y escote para luego aplicar la crema, realizando masajes de manera circular y ascendente del centro hacia arriba, complementando con suaves masajes de tecleo con las yemas de los dedos.",
      horario:"Cremas de uso diario, para cualquier momento del día!",
      quienes:"Es un producto para TODO TIPO DE PIEL, grasa, mixta, seca, sensible, con arrugas, sin arrugas, lo que se busca es el REJUVENECIMIENTO CELULAR.",
      },
  ];
